// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'core/entity/chat_message.dart';
import 'core/entity/summary.dart';
import 'core/entity/tag.dart';
import 'core/entity/vault_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7580739033913190348),
    name: 'VaultItem',
    lastPropertyId: const obx_int.IdUid(8, 5831686139283295069),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1425866417535716858),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6081127843484061721),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8209666968628807139),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1057991680229610511),
        name: 'contentText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3153857224042194992),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6284765897867116412),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3544511696730977341),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5831686139283295069),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4536474632200432481),
    name: 'Chatmessage',
    lastPropertyId: const obx_int.IdUid(5, 6649070382361571478),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6770987293488385704),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7515202287578339741),
        name: 'itemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 2153642406782319040),
        relationField: 'item',
        relationTarget: 'VaultItem',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8082652741321348896),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7447147796152483917),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6649070382361571478),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3813703148337463396),
    name: 'Summary',
    lastPropertyId: const obx_int.IdUid(5, 8703141471377506515),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6827004409739544804),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6980142364271909949),
        name: 'itemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5103864403446806710),
        relationField: 'item',
        relationTarget: 'VaultItem',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9193830053523643735),
        name: 'shortSummary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8443513821341496315),
        name: 'keyWords',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8703141471377506515),
        name: 'generatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5572251697196647784),
    name: 'Tag',
    lastPropertyId: const obx_int.IdUid(2, 3736791423240836302),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9005543710186835117),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3736791423240836302),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5572251697196647784),
    lastIndexId: const obx_int.IdUid(2, 5103864403446806710),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    VaultItem: obx_int.EntityDefinition<VaultItem>(
      model: _entities[0],
      toOneRelations: (VaultItem object) => [],
      toManyRelations: (VaultItem object) => {},
      getId: (VaultItem object) => object.id,
      setId: (VaultItem object, int id) {
        object.id = id;
      },
      objectToFB: (VaultItem object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final typeOffset = fbb.writeString(object.type);
        final contentTextOffset = object.contentText == null
            ? null
            : fbb.writeString(object.contentText!);
        final filePathOffset = object.filePath == null
            ? null
            : fbb.writeString(object.filePath!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, typeOffset);
        fbb.addOffset(3, contentTextOffset);
        fbb.addOffset(4, filePathOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.isFavorite);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = VaultItem(
          title: titleParam,
          type: typeParam,
          contentText: contentTextParam,
          filePath: filePathParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isFavorite: isFavoriteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Chatmessage: obx_int.EntityDefinition<Chatmessage>(
      model: _entities[1],
      toOneRelations: (Chatmessage object) => [object.item],
      toManyRelations: (Chatmessage object) => {},
      getId: (Chatmessage object) => object.id,
      setId: (Chatmessage object, int id) {
        object.id = id;
      },
      objectToFB: (Chatmessage object, fb.Builder fbb) {
        final roleOffset = fbb.writeString(object.role);
        final messageOffset = fbb.writeString(object.message);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.item.targetId);
        fbb.addOffset(2, roleOffset);
        fbb.addOffset(3, messageOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = Chatmessage(
          role: roleParam,
          message: messageParam,
          createdAt: createdAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.item.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.item.attach(store);
        return object;
      },
    ),
    Summary: obx_int.EntityDefinition<Summary>(
      model: _entities[2],
      toOneRelations: (Summary object) => [object.item],
      toManyRelations: (Summary object) => {},
      getId: (Summary object) => object.id,
      setId: (Summary object, int id) {
        object.id = id;
      },
      objectToFB: (Summary object, fb.Builder fbb) {
        final shortSummaryOffset = fbb.writeString(object.shortSummary);
        final keyWordsOffset = fbb.writeString(object.keyWords);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.item.targetId);
        fbb.addOffset(2, shortSummaryOffset);
        fbb.addOffset(3, keyWordsOffset);
        fbb.addInt64(4, object.generatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final shortSummaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final keyWordsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final generatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = Summary(
          shortSummary: shortSummaryParam,
          keyWords: keyWordsParam,
          generatedAt: generatedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.item.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.item.attach(store);
        return object;
      },
    ),
    Tag: obx_int.EntityDefinition<Tag>(
      model: _entities[3],
      toOneRelations: (Tag object) => [],
      toManyRelations: (Tag object) => {},
      getId: (Tag object) => object.id,
      setId: (Tag object, int id) {
        object.id = id;
      },
      objectToFB: (Tag object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Tag(name: nameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [VaultItem] entity fields to define ObjectBox queries.
class VaultItem_ {
  /// See [VaultItem.id].
  static final id = obx.QueryIntegerProperty<VaultItem>(
    _entities[0].properties[0],
  );

  /// See [VaultItem.title].
  static final title = obx.QueryStringProperty<VaultItem>(
    _entities[0].properties[1],
  );

  /// See [VaultItem.type].
  static final type = obx.QueryStringProperty<VaultItem>(
    _entities[0].properties[2],
  );

  /// See [VaultItem.contentText].
  static final contentText = obx.QueryStringProperty<VaultItem>(
    _entities[0].properties[3],
  );

  /// See [VaultItem.filePath].
  static final filePath = obx.QueryStringProperty<VaultItem>(
    _entities[0].properties[4],
  );

  /// See [VaultItem.createdAt].
  static final createdAt = obx.QueryDateProperty<VaultItem>(
    _entities[0].properties[5],
  );

  /// See [VaultItem.updatedAt].
  static final updatedAt = obx.QueryDateProperty<VaultItem>(
    _entities[0].properties[6],
  );

  /// See [VaultItem.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<VaultItem>(
    _entities[0].properties[7],
  );
}

/// [Chatmessage] entity fields to define ObjectBox queries.
class Chatmessage_ {
  /// See [Chatmessage.id].
  static final id = obx.QueryIntegerProperty<Chatmessage>(
    _entities[1].properties[0],
  );

  /// See [Chatmessage.item].
  static final item = obx.QueryRelationToOne<Chatmessage, VaultItem>(
    _entities[1].properties[1],
  );

  /// See [Chatmessage.role].
  static final role = obx.QueryStringProperty<Chatmessage>(
    _entities[1].properties[2],
  );

  /// See [Chatmessage.message].
  static final message = obx.QueryStringProperty<Chatmessage>(
    _entities[1].properties[3],
  );

  /// See [Chatmessage.createdAt].
  static final createdAt = obx.QueryDateProperty<Chatmessage>(
    _entities[1].properties[4],
  );
}

/// [Summary] entity fields to define ObjectBox queries.
class Summary_ {
  /// See [Summary.id].
  static final id = obx.QueryIntegerProperty<Summary>(
    _entities[2].properties[0],
  );

  /// See [Summary.item].
  static final item = obx.QueryRelationToOne<Summary, VaultItem>(
    _entities[2].properties[1],
  );

  /// See [Summary.shortSummary].
  static final shortSummary = obx.QueryStringProperty<Summary>(
    _entities[2].properties[2],
  );

  /// See [Summary.keyWords].
  static final keyWords = obx.QueryStringProperty<Summary>(
    _entities[2].properties[3],
  );

  /// See [Summary.generatedAt].
  static final generatedAt = obx.QueryDateProperty<Summary>(
    _entities[2].properties[4],
  );
}

/// [Tag] entity fields to define ObjectBox queries.
class Tag_ {
  /// See [Tag.id].
  static final id = obx.QueryIntegerProperty<Tag>(_entities[3].properties[0]);

  /// See [Tag.name].
  static final name = obx.QueryStringProperty<Tag>(_entities[3].properties[1]);
}
